import React, { useEffect, useState } from 'react';

import { Card, FormField, Loader } from '../components';
import { fetchPosts } from '../utils/api';
import { useToast } from '../context/ToastContext';

const RenderCards = ({ data, title }) => {
  if (data?.length > 0) {
    return (
      data.map((post) => <Card key={post._id} {...post} />)
    );
  }

  return (
    <h2 className="mt-5 font-bold text-transparent bg-clip-text bg-gradient-to-r from-blue-600 to-purple-600 text-xl uppercase">{title}</h2>
  );
};

const Home = () => {
  const { showToast } = useToast();
  const [loading, setLoading] = useState(false);
  const [allPosts, setAllPosts] = useState(null);

  const [searchText, setSearchText] = useState('');
  const [searchTimeout, setSearchTimeout] = useState(null);
  const [searchedResults, setSearchedResults] = useState(null);

  const loadPosts = async () => {
    setLoading(true);
    const result = await fetchPosts();
    
    if (result.success) {
      setAllPosts(result.data);
    } else {
      showToast(result.error || 'Failed to load posts', 'error');
    }
    
    setLoading(false);
  };

  useEffect(() => {
    loadPosts();
  }, []);

  const handleSearchChange = (e) => {
    clearTimeout(searchTimeout);
    const value = e.target.value;
    setSearchText(value);

    setSearchTimeout(
      setTimeout(() => {
        if (allPosts) {
          const searchResult = allPosts.filter((item) => 
            item.name.toLowerCase().includes(value.toLowerCase()) || 
            item.prompt.toLowerCase().includes(value.toLowerCase())
          );
          setSearchedResults(searchResult);
        }
      }, 500),
    );
  };

  return (
    <section className="max-w-7xl mx-auto">
      <div className="mb-8">
        <h1 className="font-extrabold text-transparent bg-clip-text bg-gradient-to-r from-blue-600 to-purple-600 text-5xl mb-3">
          The Community Showcase
        </h1>
        <p className="text-gray-600 text-lg max-w-[600px]">
          Browse through a collection of imaginative and visually stunning images generated by DALL-E AI
        </p>
      </div>

      <div className="mt-16">
        <FormField
          labelName="Search posts"
          type="text"
          name="text"
          placeholder="Search something..."
          value={searchText}
          handleChange={handleSearchChange}
        />
      </div>

      <div className="mt-10">
        {loading ? (
          <div className="flex justify-center items-center">
            <Loader />
          </div>
        ) : (
          <>
            {searchText && (
              <h2 className="font-medium text-gray-600 text-xl mb-3">
                Showing Results for <span className="text-gray-900 font-semibold">{searchText}</span>:
              </h2>
            )}
            <div className="grid lg:grid-cols-4 sm:grid-cols-3 xs:grid-cols-2 grid-cols-1 gap-3">
              {searchText ? (
                <RenderCards
                  data={searchedResults}
                  title="No Search Results Found"
                />
              ) : (
                <RenderCards
                  data={allPosts}
                  title="No Posts Yet"
                />
              )}
            </div>
          </>
        )}
      </div>
    </section>
  );
};

export default Home;  